require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rspec_rails

inherit_gem:
  prettier: rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - bin/**/*
    - .*/**/*
    - coverage/**/*
    - log/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/fixtures/**/*
    - spec/files/**/*
    - lint/**/*
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*

Style/IfUnlessModifier:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: true
  Max: 3

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ExampleLength:
  Enabled: true
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 15

RSpec/EmptyExampleGroup:
  Enabled: false

RSpecRails/InferredSpecType:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 12

Naming/FileName:
  Exclude:
    - '*.gemspec'

Style/NumericLiterals:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/RedundantFetchBlock:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Security/YAMLLoad:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Performance/Sum:
  Enabled: false

Performance/StringInclude:
  Enabled: false

RSpecRails/HttpStatus:
  Enabled: false

RSpecRails/HaveHttpStatus:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]
