require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - db/schema.rb
    - .gemspec/**/*
    - gemfiles/**/*
    - .bundle/**/*
    - vendor/**/*
    - db/migrate/**/*
    - '**/dummy**/*'
    - Appraisals
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/ClassLength:
  CountComments: false
  Max: 200

Layout/LineLength:
  Max: 99
  Exclude:
    - "spec/integration/rails/rails_spec.rb"

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'let']

Naming/FileName:
  Exclude:
    - '*.gemspec'
    - 'lib/castle-rb.rb'

RSpec/FilePath:
  Exclude:
    - spec/integration/
  CustomTransform:
    RuboCop: rubo_cop
    Rspec: r_spec
RSpec/MultipleExpectations:
  Enabled: true
  Max: 3
RSpec/NestedGroups:
  Enabled: true
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false

