require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - db/schema.rb
    - .gemspec/**/*
    - .bundle/**/*
    - vendor/**/*
    - '**/dummy**/*'
    - !ruby/regexp /old_and_unused\.rb$/
RSpec/FilePath:
  Exclude:
    - spec/integration/**/*
  CustomTransform:
    RuboCop: rubo_cop
    Rspec: r_spec
RSpec/MultipleExpectations:
  Enabled: true
  Max: 3
RSpec/NestedGroups:
  Enabled: true
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
