require:
  - rubocop-performance
  - rubocop-rspec

Naming/FileName:
  Exclude:
    - "lib/castle-rb.rb"

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - "lib/castle/configuration.rb"
    - "lib/castle/errors.rb"

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'let']

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 100
  Exclude:
    - "lib/castle/configuration.rb"
    - "spec/integration/rails/rails_spec.rb"

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Exclude:
    - "spec/integration/rails/rails_spec.rb"
