version: 2.1

aliases:
  - &coditsu
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker create -v /sources --name sources alpine:3.4 /bin/true
          docker cp ./ sources:/sources
          docker run \
            -e CODITSU_API_KEY \
            -e CODITSU_API_SECRET \
            -e CODITSU_REPOSITORY_ID \
            --volumes-from sources coditsu/coditsu:latest
  - &rails-5
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_5.gemfile
  - &rails-6
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_6.gemfile
  - &ruby-2_4_9
    docker:
    - image: circleci/ruby:2.4.9
  - &ruby-2_5_7
    docker:
    - image: circleci/ruby:2.5.7
  - &ruby-2_6_5
    docker:
    - image: circleci/ruby:2.6.5
  - &ruby-2_7
    docker:
    - image: circleci/ruby:2.7
  - &ruby-3_0
    docker:
    - image: circleci/ruby:3.0
  - &job-defaults
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rake

jobs:
  coditsu:
    <<: *rails-5
    <<: *coditsu
  ruby-2_4_9-rails-5:
    <<: *ruby-2_4_9
    <<: *rails-5
    <<: *job-defaults
  ruby-2_5_7-rails-5:
    <<: *ruby-2_5_7
    <<: *rails-5
    <<: *job-defaults
  ruby-2_5_7-rails-6:
    <<: *ruby-2_5_7
    <<: *rails-6
    <<: *job-defaults
  ruby-2_6_5-rails-5:
    <<: *ruby-2_6_5
    <<: *rails-5
    <<: *job-defaults
  ruby-2_6_5-rails-6:
    <<: *ruby-2_6_5
    <<: *rails-6
    <<: *job-defaults
  ruby-2_7-rails-5:
    <<: *ruby-2_7
    <<: *rails-5
    <<: *job-defaults
  ruby-2_7-rails-6:
    <<: *ruby-2_7
    <<: *rails-6
    <<: *job-defaults
  ruby-3_0-rails-6:
    <<: *ruby-3_0
    <<: *rails-6
    <<: *job-defaults
workflows:
  main:
    jobs:
      - coditsu
      - ruby-2_4_9-rails-5
      - ruby-2_5_7-rails-5
      - ruby-2_5_7-rails-6
      - ruby-2_6_5-rails-5
      - ruby-2_6_5-rails-6
      - ruby-2_7-rails-5
      - ruby-2_7-rails-6
      - ruby-3_0-rails-6
