version: 2.1

aliases:
  - &coditsu
    docker:
      - image: cimg/ruby:3.3
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker create -v /sources --name sources alpine:3.4 /bin/true
          docker cp ./ sources:/sources
          docker run \
            -e CODITSU_API_KEY \
            -e CODITSU_API_SECRET \
            -e CODITSU_REPOSITORY_ID \
            --volumes-from sources coditsu/coditsu:latest
  - &rails-6
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_6.gemfile
  - &rails-7
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_7.gemfile
  - &ruby-2_7
    docker:
    - image: cimg/ruby:2.7
  - &ruby-3_0
    docker:
    - image: cimg/ruby:3.0
  - &ruby-3_1
    docker:
      - image: cimg/ruby:3.1
  - &ruby-3_2
    docker:
      - image: cimg/ruby:3.2
  - &ruby-3_3
    docker:
      - image: cimg/ruby:3.3
  - &job-defaults
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rake

jobs:
  coditsu:
    <<: *rails-7
    <<: *coditsu
  ruby-2_7-rails-6:
    <<: *ruby-2_7
    <<: *rails-6
    <<: *job-defaults
  ruby-3_0-rails-6:
    <<: *ruby-3_0
    <<: *rails-6
    <<: *job-defaults
  ruby-3_0-rails-7:
    <<: *ruby-3_0
    <<: *rails-7
    <<: *job-defaults
  ruby-3_1-rails-7:
    <<: *ruby-3_1
    <<: *rails-7
    <<: *job-defaults
  ruby-3_2-rails-7:
    <<: *ruby-3_2
    <<: *rails-7
    <<: *job-defaults
  ruby-3_3-rails-7:
    <<: *ruby-3_3
    <<: *rails-7
    <<: *job-defaults
workflows:
  main:
    jobs:
      - coditsu:
          context:
            - coditsu
      - ruby-2_7-rails-6
      - ruby-3_0-rails-6
      - ruby-3_0-rails-7
      - ruby-3_1-rails-7
      - ruby-3_2-rails-7
      - ruby-3_3-rails-7
