version: 2.1

aliases:
  - &ruby-3_2
    docker:
      - image: cimg/ruby:3.2
  - &ruby-3_3
    docker:
      - image: cimg/ruby:3.3
  - &ruby-3_4
    docker:
      - image: cimg/ruby:3.4
  - &rails-7_0
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_7.0.gemfile
  - &rails-7_1
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_7.1.gemfile
  - &rails-7_2
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_7.2.gemfile
  - &rails-8_0
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_8.0.gemfile
  - &rails-8_1
    environment:
      BUNDLE_GEMFILE: gemfiles/rails_8.1.gemfile
  - &job-defaults
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rspec
  - &lint-defaults
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install --jobs=4 --retry=3
      - run: bundle exec rubocop

jobs:
  rubocop:
    <<: *ruby-3_4
    <<: *lint-defaults
  ruby-3_2-rails-7_0:
    <<: *ruby-3_2
    <<: *rails-7_0
    <<: *job-defaults
  ruby-3_2-rails-7_1:
    <<: *ruby-3_2
    <<: *rails-7_1
    <<: *job-defaults
  ruby-3_2-rails-7_2:
    <<: *ruby-3_2
    <<: *rails-7_2
    <<: *job-defaults
  ruby-3_3-rails-7_1:
    <<: *ruby-3_3
    <<: *rails-7_1
    <<: *job-defaults
  ruby-3_3-rails-7_2:
    <<: *ruby-3_3
    <<: *rails-7_2
    <<: *job-defaults
  ruby-3_3-rails-8_0:
    <<: *ruby-3_3
    <<: *rails-8_0
    <<: *job-defaults
  ruby-3_4-rails-8_0:
    <<: *ruby-3_4
    <<: *rails-8_0
    <<: *job-defaults
  ruby-3_4-rails-8_1:
    <<: *ruby-3_4
    <<: *rails-8_1
    <<: *job-defaults

workflows:
  main:
    jobs:
      - rubocop
      - ruby-3_2-rails-7_0
      - ruby-3_2-rails-7_1
      - ruby-3_2-rails-7_2
      - ruby-3_3-rails-7_1
      - ruby-3_3-rails-7_2
      - ruby-3_3-rails-8_0
      - ruby-3_4-rails-8_0
      - ruby-3_4-rails-8_1
